vile:
  ignore: [
      "node_modules",
      "coverage",
      "tags",
      ".ctags",
      "test/fixtures/**",
      ".test",
      ".git",
      ".eslintrc",
      ".eslintignore",
      ".fs-lint",
      ".npmignore",
      ".gitignore",
      ".vilerc",
      ".vile.yml",
      "circle.yml",
      "coffeelint.json",
      "/lib"
    ]

depcheck:
  config:
    ignore_dev_deps: false
    ignore_dirs: [ ]
    ignore_deps: [
        "pryjs",
        "bluebird",
        "@forthright/*"
      ]

coverage:
  config:
    path: coverage/lcov.info

coffeelint:
  config: coffeelint.json

length:
  config:
    file: 250
    line: 80
  ignore: [ "lib" ]

license:
  config:
    ignored: [ "tslint" ]
    disallowed: [ ]
    allowed: [
      "MIT",
      "MPL",
      "MPL-2.0",
      "Public Domain",
      "PSF",
      "BSD",
      "BSD-3-Clause",
      "BSD-2-Clause",
      "Unlicense",
      "Artistic-2.0",
      "ISC",
      "WTFPL",
      "Apache",
      "Apache-2.0",
      "Apache 2.0",
      "Apache*",
      "Apachev2",
      "WTFPL",
      "GPL"
    ]
